[package]
name = "StakePackage"
version = "1.0.0"
authors = []

[addresses]
stake_package                       = "0xde8dccd14c681e868d062dab335cdb26c8177b238935f9d38d13909a3e79b615"
amnis                               = "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a"

amnis_fungible_USDC                 = "0xbae207659db88bea0cbead6da0ed00aac12edcdda169e591cd41c94180b46f3b"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies]
amnis                 = { local = "deps/amnis" }
                     
[dev-dependencies]
