[package]
name = "hedos-interact-lending"
version = "1.0.0"
authors = []

[addresses]
hedos                   = "0xb9043885f5adaecebb0cd03716cd22fc364f375cd58c6f5729ad21158a8de25a"
wrapped_coins           = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]

[dependencies]
Aries               = { local = "../deps/Aries" }
Oracle              = { local = "../deps/Oracle" }
Decimal             = { local = "../deps/Decimal" }
hedos-interact-swap = { local = "../hedos-interact-swap" }
WrappedCoins        = { local = "../deps/WrappedCoins" }
hedos-utils         = { local = "../hedos-utils" }