[package]
name = "hedos-interact-lending"
version = "1.0.0"
authors = []

[addresses]
hedos                   = "0x005cb1912b90a282682ab49dc86d3379b75e4bb8094ecc4637f44d19c80ddd71"
wrapped_coins           = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]

[dependencies]
Aries               = { local = "../deps/Aries" }
Oracle              = { local = "../deps/Oracle" }
Decimal             = { local = "../deps/Decimal" }
hedos-interact-swap = { local = "../hedos-interact-swap" }
WrappedCoins        = { local = "../deps/WrappedCoins" }
hedos-utils         = { local = "../hedos-utils" }
hedos-router-vault  = { local = "../hedos-router-vault" }