[package]
name = "hedos-interact-liquid"
version = "1.0.0"
authors = []

[addresses]
hedos                   = "0x005cb1912b90a282682ab49dc86d3379b75e4bb8094ecc4637f44d19c80ddd71"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]

[dependencies]
amnis               = { local = "../deps/amnis" }
hedos-interact-swap = { local = "../hedos-interact-swap" }
hedos-utils         = { local = "../hedos-utils" }
hedos-router-vault  = { local = "../hedos-router-vault" }