[package]
name = "Trading_Package"
version = "1.0.0"
authors = []

[addresses]
trading_package                     = "0xde8dccd14c681e868d062dab335cdb26c8177b238935f9d38d13909a3e79b615"
merkle                              = "0x5ae6789dd2fec1a9ec9cccfb3acaf12e93d432f0a3a42c92fe1a9d490b7bbc06"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies]
merkle              = { local = "deps/merkle" }
merkle-common       = { local = "deps/merkle-common" }
                     
[dev-dependencies]
