[package]
name = "contracts"
version = "1.0.0"
authors = []

[addresses]
fauz   = "0x3d4d0c5a1467ba82881e89b21bfabd85f38225ccbf27309ebdd6d61417923d64"
merkle = "0x5ae6789dd2fec1a9ec9cccfb3acaf12e93d432f0a3a42c92fe1a9d490b7bbc06"
amnis = "0x111ae3e5bc816a5e63c2da97d0aa3886519e0cd5e4b046659fa35796bd11542a"
delta_hedging = "70e9853c05beac263a6fee5dd46989540dc59694ec84456c79f1751da803e102"
pancakeswap = "0xc7efb4076dbe143cbcd98cfaaa929ecfc8f299203dfff63b95ccb6bfe19850fa"
multi_router = "0x9dd974aea0f927ead664b9e1c295e4215bd441a9fb4e53e5ea0bf22f356c8a2b"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]

[dependencies]
merkle = { local = "../deps/merkle" }
merkle-common = { local = "../deps/merkle-common" }
amnis = {local = "../deps/amnis" }
PancakeSwap = { local = "../deps/PancakeSwap" }
MultiRouter = { local = "../deps/MultiRouter" }
