[package]
name = "Aries"
version = "0.0.0"
published-at = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"

[addresses]
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"
aries = "0x9770fa9c725cbd97eb50b2be5f7416efdfd1f1554beb0750d4dae4c64e860da3"

# Mainnet named addresses
hippo_aggregator = "0x890812a6bbe27dd59188ade3bbdbe40a544e6e104319b7ebc6617d3eb947ac07"

[dependencies]

[dependencies.HippoAggregator]
git = "https://github.com/Aries-Markets/hippo-agg-interface.git"
subdir = "."
rev = "main"